name: demo_workflow

on:
  push:
    branches:
    - 'main'

jobs:
  demo-job:
    name: demo_job
    runs-on: ubuntu-latest
    steps:
      - name: message 1
        run: echo "this is message 1"
      - name: message 2
        run: echo "this is message 2"
